### ISSUE TITLE
Downloading MODIS data issues with getHdf 

### ISSUE THREAD

**Issue by mkettley** [fdetsch/MODIS#102]
I'm trying to download MOD16A2 data. As a precursor to what I need I am running the following code:

```
hdf = getHdf("MOD16A2", begin = "2017.01.01", end = "2017.01.10"
                           , tileH = 21, tileV = 8)
```

However when I run this I get the following error repeated multiple times:

```
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
```

Any advice would be great, thanks.

**Comment by fdetsch** [comment]
Have you tried this with the latest development version? This might help narrow down the issue a little bit..

```r
remotes::install_github("MatMatt/MODIS", ref = "develop")
library(MODIS)
```
