### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [fdetsch/MODIS#130]
This package and satellite depend on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by fdetsch** [comment]
Thanks. The dependencies were eliminated in #131 . I'll update the package on CRAN as soon as #132 has been resolved, i.e. (hopefully) until 2023-01-09.

**Comment by rsbivand** [comment]
@fdetsch  rgdal was archived two days ago, so please do move to submit an updated version of satellite as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details.
