### ISSUE TITLE
mask values doesn't work for multiple tiles and "average" resampling

### ISSUE THREAD

**Issue by MagicForrest** [fdetsch/MODIS#70]
Hi guys, thanks again for the awesome package.  It is great to have a one-stop shop for MODIS in R.  Unfortunately, I have an issue to do with the masking of no data values.  I should really have reported this after we implemented the error code/no data value masking last year, but somehow I didn't and then it slipped off the agenda.

The problem is that using maskValue doesn't work when combining multiple MODIS tiles and "average" resampling.  

For a single tile it works fine (example is based om fdetsch's from #39 except I use fpar because is more clearly bounded at 100%), but it doesn't work well for two tiles.  It also works fine for resamplingType="mode" (why is maybe why it wasn't picked up before).  Here is a reprex:

``` r
devtools::install_github("MatMatt/MODIS", ref = "develop")
#> Skipping install of 'MODIS' from a github remote, the SHA1 (9cf9944c) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(MODIS)
#> Loading required package: mapdata
#> Loading required package: maps
#> Loading required package: raster
#> Loading required package: sp
library(raster)

MODISoptions(resamplingType = "average")
#> 
#> STORAGE:
#> _______________
#> localArcPath : /data/forrest 
#> outDirPath   : /data/forrest/LAI/MCD15A3.006.2003.masked.GTiff.native 
#> 
#> 
#> DOWNLOAD:
#> _______________
#> MODISserverOrder : LAADS 
#> dlmethod         : wget 
#> stubbornness     : high 
#> wait             : 0.5 
#> quiet            : FALSE 
#> 
#> 
#> PROCESSING:
#> _______________
#> GDAL           : GDAL 2.2.2, released 2017/09/15 
#> MRT            : Version 4.1 (March 2011) 
#> pixelSize      : asIn 
#> outProj        : asIn 
#> resamplingType : average 
#> dataFormat     : GTiff 
#> cellchunk      : 1

# run only one tile
fpar1 = runGdal("MCD15A2H", tileH = 21, tileV = 8
              , begin = "2003001", end = "2003008"
              , SDSstring = "1", job = "mcd15a2h-test_onetile"
              , maskValue = 249:255, overwrite = TRUE)
#> ########################
#> outProj          =  asIn 
#> pixelSize        =  asIn 
#> resamplingType   =  average 
#> Output Directory =  /data/forrest/LAI/MCD15A3.006.2003.masked.GTiff.native/mcd15a2h-test_onetile 
#> ########################
#> Local structure is up-to-date. Using offline information!
#> Warning in readLines(nrc): incomplete final line found on '/home/
#> forrest/.netrc'

rst1 = raster(fpar1[[1]][[1]])
(tbl1 <- table(rst1[]))[order(as.numeric(names(tbl1)), decreasing = TRUE)][1:10]
#> 
#>  100   99   98   97   96   95   94   93   92   91 
#>  656   52   65   92  309  613 1503 1381 1436 6216
print(plot(rst1))
```

![](https://i.imgur.com/6qOz1na.png)

    #> NULL
    
    # all good, no values greater than 100
    
    # run two tiles
    fpar2 = runGdal("MCD15A2H", tileH = 21, tileV = c(7,8)
                  , begin = "2003001", end = "2003008"
                  , SDSstring = "1", job = "mcd15a2h-test_twotile"
                  , maskValue = 249:255, overwrite = TRUE)
    #> ########################
    #> outProj          =  asIn 
    #> pixelSize        =  asIn 
    #> resamplingType   =  average 
    #> Output Directory =  /data/forrest/LAI/MCD15A3.006.2003.masked.GTiff.native/mcd15a2h-test_twotile 
    #> ########################
    #> Local structure is up-to-date. Using offline information!
    #> Warning in readLines(nrc): incomplete final line found on '/home/
    #> forrest/.netrc'
    
    rst2 = raster(fpar2[[1]][[1]])
    (tbl2 <- table(rst2[]))[order(as.numeric(names(tbl2)), decreasing = TRUE)][1:10]
    #> 
    #> 213 212 211 210 209 208 207 206 205 204 
    #> 132 142  92  57  95 131 191 219 249 278
    
    print(plot(rst2))

![](https://i.imgur.com/44BStfP.png)

    #> NULL
    
    # issue, get values greater than 100

<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

There are definitely non-sensibles values in there ( >100), but they are not exactly the MODIS error codes (248:255).  So I guess that some averaging is getting done *before* the value replacing.  This surprised me since the outProj and pixelSize are both "asIn", so I thought no averaging needed to be done.  By maybe there is averaging done from 500m resolution to 1km as part of the process?

There is an additional error message that doesn't show up on the reprex but shows up when I run the code normally, I think it might be also important.

```r 
Usage: val_repl.py -innd in_nodata_value -outnd out_nodata_value
                   [-of out_format] [-ot out_type] infile outfile
```

Digging around the in the runGdal()  function, I might  see the problem.  The val_repl.py script doesn't take multiple input files, like the normal GDAL commands do.

So, I guess the solution would involve swapping the order of the operations so that the value masking is done before the resampling.  And possibly do the value masking for each tile individually before doing the gdalwarp. That might hurt performance (almost certainly), but for my perspective it would be worth it to make sure that the non-value pixels are not getting interpreted as data.

I would consider having a go at this myself and making a pull request (because I think this is pretty important for my workflow), but I would also be super-happy if one of the experienced developers of the package had a look instead ;-).

**Comment by MagicForrest** [comment]
Bump.  Is there any chance of a fix here?  I notice that the "maskValue" argument for runGdal() is not marked as "not currently used".  Does that mean that mean it is unfeasible to implement it, or it is on the To-Do list? 

Sorry to bug you about it again, but now I have a PhD student running into the same problem so it has become an issue again.  I notice that I did offer to potentially try and fix it myself.  Is that something you are interested in?

**Comment by fdetsch** [comment]
I would have to have a closer look at this in order to answer your question properly. The truth right now is that **MODIS** is not exactly on top of my to-do list, so I'd highly appreciate if you or your PhD student could have a look at this and submit a PR, if possible.

**Comment by MagicForrest** [comment]
Hi Florian.  Understood!  This is currently beyond my student's ability level.  We'll work around it for just now, but I'll put it on my To-Do list.  I guess that when it becomes critical for me I will be suitably motivated to do it ;-)

**Comment by fdetsch** [comment]
Excellent, really appreciate it!

**Comment by fdetsch** [comment]
The problem with `gdalwarp` is that you cannot assign multiple `-srcnodata` values to a single band (see the [documentation](https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-srcnodata), [StackExchange](https://gis.stackexchange.com/q/339709), etc.). Due to that, we had initially implemented an approach leveraging [val_repl.py](https://github.com/OSGeo/gdal/blob/master/swig/python/gdal-utils/osgeo_utils/samples/val_repl.py) to replace all user-defined mask values with the "official" `NoData Value` per band before the actual warping. This approach has been abandoned a while back because it was not realizable through `sf::gdal_utils()` and would hence have required manual Python (dependency) management by the package itself. 

There's other options to get rid of undesired values right before the warping step, e.g. via [`gdal_calc.py`](https://gis.stackexchange.com/questions/200464/how-to-replace-pixel-values-in-a-single-band-dem), but this still doesn't solve the dependency problem. In fact, when executing the following `system()` call, 

```sh
gdal_calc.py \
    -A HDF4_EOS:EOS_GRID:\"/home/fdetsch/Documents/data/MODIS_ARC/MODIS/MCD15A2H.061/2003.01.01/MCD15A2H.A2003001.h21v08.061.2020085220319.hdf\":MOD_Grid_MOD15A2H:Fpar_500m \
    --calc='(A<249)*A+(A>=249)*0' \
    --outfile=/home/fdetsch/Documents/data/MODIS_ARC/PROCESSED/mcd15a2h-test_onetile/MCD15A2H.A2003001.Fpar_500m.tif \
    --NoDataValue=255 \
    --overwrite
```

I just ran into the following error myself:

```py
  File "/usr/local/bin/gdal_calc.py", line 5, in <module>
    from osgeo_utils.gdal_calc import *  # noqa
ModuleNotFoundError: No module named 'osgeo_utils'
```

Of course, a user that is somewhat familiar with Python will quickly realize that this requires nothing more than `pip install gdal`. But truth be told, I would consider this to go beyond the scope of **MODIS**. 

For you to assert multiple mask values per band, the easiest would be a semi-manual approach that first leverages `runGdal()` to download and mosaic the single tiles followed by a **terra** (or **raster**) based post-processing to eliminate all desired mask values:

```r
# remotes::install_github("fdetsch/MODIS")
library(MODIS)
library(terra)

MODISoptions(
  resamplingType = "near"
)

fpar2 = runGdal(
  product
  , collection = clc
  , tileH = 21
  , tileV = c(7, 8)
  , begin = "2003001"
  , end = "2003031"
  , SDSstring = "1"
  , job = "mcd15a2h-test_twotile"
  , overwrite = TRUE
)


rst2 = rast(
  unlist(
    fpar2
  )
)

msk2 = mask(
  rst2
  , mask = rst2 > 100 # TRUE = 1L, FALSE = 0L
  , maskvalue = 1L
)

plot(
  msk2
  , zlim = c(0, 100)
  , main = basename(
    sources(
      rst2
    )
  )
)
```

![image](https://user-images.githubusercontent.com/3940660/190988208-f012883b-00a1-47cf-86db-c3e4317b9dec.png)

**Comment by MagicForrest** [comment]
Thanks for this.  I kinda expected that the conclusion might be "beyond the scope of MODIS", I was asking for a lot!  

I can definitely follow your suggestion and work up solutions as you demonstrate with terra.  I will also need to do resampling and reprojecting as a subsequent processing step too (which was why I was hoping to get it all with a single "runGdal()" command).  But this will be much easier and more efficient with terra than with raster.  Already the MODIS package provides in great service by facilitating the first steps in the chain with a single command.  Many thanks again!

**Comment by fdetsch** [comment]
Thanks. Indeed, **terra** should offer sufficient and fast enough functionality for post-processing.

I'll at least try to make the documentation for `maskValue` a bit more transparent and align the code with what is described in the [gdalwarp -srcnodata documentation](https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-srcnodata).
